version: "3.1"
services:
  java:
    build:
      context: .
    depends_on:
      - "db"
    ports:
      - "8080:8080"
  db:
    image: postgres
    ports:
      - '5432:5432'
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_DB: currency
      POSTGRES_USER: currency
      POSTGRES_PASSWORD: currency
    restart: always


